version: "3.3"
services:
  gateway:
    build: ./api-gateway
    network_mode: host
    image: gateway-image
    container_name: gateway-container
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-southeast-1
        awslogs-group: social-media-ec2-dockerlogs
        awslogs-stream: gateway-service-logs
    env_file:
      - /home/ubuntu/Environment/api-gateway.env

  userservice:
    build: ./user-service
    network_mode: host
    depends_on:
      - gateway
    image: user-service-image
    container_name: user-service-container
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-southeast-1
        awslogs-group: social-media-ec2-dockerlogs
        awslogs-stream: user-service-logs
    env_file:
      - /home/ubuntu/Environment/user-service.env

  connectservice:
    build: ./connection-service
    network_mode: host
    depends_on:
      - gateway
    image: connect-service-image
    container_name: connect-service-container
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-southeast-1
        awslogs-group: social-media-ec2-dockerlogs
        awslogs-stream: connect-service-logs
    env_file:
      - /home/ubuntu/Environment/connection-service.env

  chatservice:
    build: ./chat-service
    network_mode: host
    depends_on:
      - gateway
    image: chat-service-image
    container_name: chat-service-container
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-southeast-1
        awslogs-group: social-media-ec2-dockerlogs
        awslogs-stream: chat-service-logs
    env_file:
      - /home/ubuntu/Environment/chat-service.env
